version: "2"

services:
  dev:
    build:
      context: .
    volumes:
      - .:/code
    volumes_from:
      - elm-stuff
    ports:
      - "8000:8000"

  elm-stuff:
    image: busybox
    volumes:
      - /code/elm-stuff
